## 1) Create a null vector of size 10 but the fifth value which is 1.


In [52]:
import numpy as np
a = np.zeros(10,int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [56]:
ar = (np.arange(10)==4).astype(int)
print(ar)

[0 0 0 0 1 0 0 0 0 0]


In [59]:
arr = np.array([int(x==4) for x in range(10)])
print(arr)

[0 0 0 0 1 0 0 0 0 0]


## 2) Create a vector with values ranging from 10 to 49.


In [62]:
import numpy as np
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [63]:
import numpy as np
b = np.arange(10,50).reshape(4,10)
print(b)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [64]:
import numpy as np
b = np.arange(10,50).reshape(8,5)
print(b)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


## 3) Create a 3x3 matrix with values ranging from 0 to 8


In [65]:
import numpy as np
c = np.random.randint(9,size=(3,3))
print(c)

[[3 1 8]
 [8 0 2]
 [6 5 8]]


In [70]:
import numpy as np
c1 = np.arange(9).reshape(3,3)
print(c1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 4) Find indices of non-zero elements from [1,2,0,0,4,0]


In [74]:
import numpy as np
arra = np.array([1,2,0,0,4,0])
k = np.nonzero(arra)
print('The non zero numbers are :\n',arra[k])
print('The indices of non zero numbers are :\n',k) 

The non zero numbers are :
 [1 2 4]
The indices of non zero numbers are :
 (array([0, 1, 4], dtype=int64),)


## 5) Create a 10x10 array with random values and find the minimum and maximum values.


In [81]:
import numpy as np
arr = np.random.random((10,10))
print('The original array: \n',arr)
print('The min value of array is :\n',arr.min(),'\nThe max value of array is :\n',arr.max())

The original array: 
 [[0.1220981  0.1557276  0.76999998 0.91926719 0.57183091 0.59851424
  0.23473453 0.15204248 0.01574051 0.67810408]
 [0.09784371 0.38738609 0.97366611 0.85472575 0.39392458 0.6431764
  0.89928991 0.70048564 0.19864564 0.47404553]
 [0.72339275 0.17265351 0.12435019 0.06407715 0.07888658 0.15283391
  0.25412393 0.74401137 0.75997966 0.90471822]
 [0.52371515 0.35827774 0.15727416 0.09954344 0.10574038 0.42594402
  0.67922009 0.83317624 0.06416378 0.16755283]
 [0.2249202  0.96382555 0.05094561 0.67587922 0.31430957 0.81759486
  0.35697296 0.63361277 0.8466747  0.67061317]
 [0.78404018 0.86304565 0.81913392 0.95291544 0.92164638 0.92253786
  0.41821435 0.6983283  0.94684565 0.32427044]
 [0.41387221 0.24967323 0.0612897  0.16935283 0.53189306 0.20117081
  0.46045789 0.93480234 0.18307546 0.79664039]
 [0.4047324  0.30274493 0.30404723 0.21089077 0.23098304 0.97200058
  0.60832069 0.56479886 0.54098152 0.95553144]
 [0.14974367 0.12875949 0.04780581 0.56646258 0.87638701 0.

## 6) Create a random vector of size 30 and find the mean value.


In [92]:
import numpy as np
c = np.random.random(30).reshape(3,10)
print(c)
print(np.mean(c))

[[0.1112765  0.53543897 0.30405625 0.38127224 0.94197304 0.67779572
  0.54428581 0.66059209 0.62292102 0.9465843 ]
 [0.14280426 0.04588744 0.08445823 0.125955   0.58536929 0.77237262
  0.46029881 0.15454174 0.7806098  0.67581831]
 [0.04266349 0.53126556 0.67921223 0.11649533 0.11500168 0.24572202
  0.57936028 0.91255766 0.46613087 0.31543816]]
0.45193862284700803


In [89]:
import numpy as np
arr2 = np.random.random((6,5))
print(arr2)
print(np.mean(arr2))

[[0.43933406 0.0089172  0.10846337 0.94638219 0.33902309]
 [0.40801809 0.52041166 0.55621208 0.57229394 0.13712265]
 [0.02580001 0.9663615  0.18255457 0.29478854 0.80078947]
 [0.38994187 0.89456385 0.57575124 0.38297933 0.45684748]
 [0.73807993 0.02813321 0.69175549 0.07739217 0.35481388]
 [0.91795025 0.94994705 0.9792779  0.80393015 0.39751468]]
0.498178363474635


In [87]:
import numpy as np
arr2 = np.random.random((6,5))
print(arr2)
print(arr2.mean())

[[0.14173298 0.12214235 0.05122989 0.08891262 0.97372283]
 [0.83389491 0.77974816 0.24639416 0.78815326 0.51678613]
 [0.69286216 0.91359297 0.77133425 0.85007742 0.67557244]
 [0.71391901 0.92402186 0.2453455  0.30740265 0.19672258]
 [0.93309233 0.1644399  0.20950009 0.05758691 0.87826449]
 [0.19854322 0.99859642 0.39980075 0.77434576 0.69224517]]
0.5379994387347156
